"""
URL configuration for config project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('apps.accounts.urls')),      # auth & profile
    path('api/chat/', include('apps.chat.urls')),      # chat functionality
]
