export const chatThreads = [
  {
    id: 1,
    name: "Maya Rivers",
    initials: "MR",
    color: "#7C3AED",
    lastMessage: "Just sent the latest designs — check the pinned note.",
    time: "9:12 AM",
    unread: 4,
  },
  {
    id: 2,
    name: "Noah Kim",
    initials: "NK",
    color: "#2563EB",
    lastMessage: "The launch plan is ready. I’ll share the deck soon.",
    time: "8:47 AM",
    unread: 0,
  },
  {
    id: 3,
    name: "Elena Ortiz",
    initials: "EO",
    color: "#F97316",
    lastMessage: "Can we move the review call to tomorrow afternoon?",
    time: "Yesterday",
    unread: 2,
  },
  {
    id: 4,
    name: "Robin Gray",
    initials: "RG",
    color: "#059669",
    lastMessage: "I added the missing microcopy suggestions to the doc.",
    time: "Mon",
    unread: 0,
  },
];

export const communityThreads = [
  {
    id: 1,
    name: "Product Launch",
    initials: "PL",
    color: "#14B8A6",
    description: "Cross-team planning for the next release.",
    members: 520,
    unread: 6,
  },
  {
    id: 2,
    name: "Design Systems",
    initials: "DS",
    color: "#8B5CF6",
    description: "Component updates and accessibility reviews.",
    members: 214,
    unread: 0,
  },
  {
    id: 3,
    name: "Remote Culture",
    initials: "RC",
    color: "#F59E0B",
    description: "Ideas for meetings, onboarding, and async work.",
    members: 1340,
    unread: 3,
  },
  {
    id: 4,
    name: "Weekend Hikes",
    initials: "WH",
    color: "#EF4444",
    description: "Plan weekend trips with the team.",
    members: 78,
    unread: 0,
  },
];
